// <auto-generated />
using System;
using BlazorPortfolio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorPortfolio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328072557_AddSiteProfile")]
    partial class AddSiteProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BlazorPortfolio.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Acme Corp",
                            Description = "Led development of cloud-native applications.",
                            Period = "2022 - Present",
                            SortOrder = 1,
                            Title = "Senior Developer"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Startup Inc",
                            Description = "Built and maintained web applications using .NET and React.",
                            Period = "2019 - 2022",
                            SortOrder = 2,
                            Title = "Full Stack Developer"
                        });
                });

            modelBuilder.Entity("BlazorPortfolio.Models.HiringMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HiringMessages");
                });

            modelBuilder.Entity("BlazorPortfolio.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This very portfolio, built with Blazor and EF Core.",
                            SortOrder = 1,
                            TechStack = "Blazor, EF Core, SQLite",
                            Title = "Portfolio CMS"
                        });
                });

            modelBuilder.Entity("BlazorPortfolio.Models.SiteProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactBlurb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Eyebrow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroCta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSecondaryCta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactBlurb = "Have an opportunity or just want to say hi? Fill out the form and I'll get back to you.",
                            Email = "hello@example.com",
                            Eyebrow = "👋 Welcome to my portfolio",
                            HeroCta = "Hire Me",
                            HeroSecondaryCta = "View Projects",
                            Location = "Your City, Country",
                            OwnerName = "Your Name",
                            Tagline = "Full Stack Developer · .NET · Blazor · Cloud"
                        });
                });

            modelBuilder.Entity("BlazorPortfolio.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Name = "C# / .NET",
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 2,
                            Category = "Frontend",
                            Name = "Blazor",
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            Name = "SQL / EF Core",
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 4,
                            Category = "DevOps",
                            Name = "Docker",
                            Proficiency = 70
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
